#!/usr/bin/env python3
"""Bundle the modular Content Script into a classic browser script."""

from pathlib import Path
import re
import sys


IMPORT_RE = re.compile(r"^\s*import\s+(?:[^;\n]+?\s+from\s+)?['\"](.+?)['\"]\s*;?\s*$", re.MULTILINE)
EXPORT_RE = re.compile(r"\bexport\s+(?=(?:async\s+)?(?:function|class|const|let|var)\b)")


def bundle(entry: Path) -> str:
    visited: set[Path] = set()
    chunks: list[str] = ["// Generated by scripts/bundle-content.py; source modules remain under src/.\n"]

    def visit(path: Path) -> None:
        path = path.resolve()
        if path in visited:
            return
        if not path.is_file():
            raise FileNotFoundError(f"missing local module: {path}")
        visited.add(path)
        source = path.read_text(encoding="utf-8")
        imports = list(IMPORT_RE.finditer(source))
        for match in imports:
            import_path = match.group(1)
            dependency = Path(import_path)
            if dependency.is_absolute() or not (import_path.startswith('./') or import_path.startswith('../')):
                raise ValueError(f"only relative local imports are supported: {import_path}")
            visit((path.parent / dependency).resolve())
        body = IMPORT_RE.sub("", source)
        body = EXPORT_RE.sub("", body)
        body = re.sub(r"\bexport\s+default\s+", "", body)
        chunks.append(f"\n// --- {path.name} ---\n{body.rstrip()}\n")

    visit(entry)
    return "".join(chunks)


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {Path(sys.argv[0]).name} ENTRY OUTPUT", file=sys.stderr)
        return 2
    output = Path(sys.argv[2])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(bundle(Path(sys.argv[1])), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
